import { RouteRecordRaw } from "vue-router"
const routes:RouteRecordRaw[]=[
    {
        path:"/",
        name:"Home",
        component:()=>import("@/layouts/DefaultLayout.vue"),
        redirect:"/dashboard",
        children:[
            {
                path:"/dashboard",
                name:"dashboard",
                component:()=>import("@/views/dashboard/DashBoard.vue")
            },
            {
                path:"/chargingstation/monitor",
                name:"monitor",
                component:()=>import("@/views/chargingstation/Monitor.vue")
            },
            {
                path:"/chargingstation/revenue",
                name:"revenue",
                component:()=>import("@/views/chargingstation/Revenue.vue")
            },
            {
                path:"/chargingstation/fault",
                name:"fault",
                component:()=>import("@/views/chargingstation/Fault.vue")
            },
            {
                path:"/chargingstation/pile-management",
                name:"pile-management",
                component:()=>import("@/views/chargingstation/PileManagement.vue")
            },
            {
                path:"/map",
                name:"map",
                component:()=>import("@/views/map/ElectronicMap.vue")
            },
            {
                path:"/operations/orders",
                name:"orders",
                component:()=>import("@/views/operations/Orders.vue"),
                meta:{
                    keepAlive:true
                }
            },
            {
                path:"/operations/detail",
                name:"detail",
                component:()=>import("@/views/operations/Detail.vue")
            },
            {
                path:"/operations/total",
                name:"total",
                component:()=>import("@/views/operations/Total.vue")
            },
            {
                path:"/alarm",
                name:"alarm",
                component:()=>import("@/views/alarm/Alarm.vue")
            },
            {
                path:"/equipment",
                name:"equipment",
                component:()=>import("@/views/equipment/Equipment.vue"),   
            },
            {
                path:"/document",
                name:"document",
                component:()=>import("@/views/document/Document.vue"),
                meta:{
                    needAuth:["admin","manager"]
                }
            },
            {
                path:"/system",
                name:"system",
                component:()=>import("@/views/system/System.vue"),
                meta:{
                    needAuth:["admin"]
                }
            },
            {
                path:"/personal",
                name:"personal",
                component:()=>import("@/views/personal/Personal.vue")
            },
            // Web监控模块
            {
                path:"/web-monitor/overview",
                name:"webmonitor-overview",
                component:()=>import("@/views/webMonitor/Overview.vue"),
            },
            {
                path:"/web-monitor/performance",
                name:"webmonitor-performance",
                component:()=>import("@/views/webMonitor/Performance.vue"),
            },
            {
                path:"/web-monitor/errors",
                name:"webmonitor-errors",
                component:()=>import("@/views/webMonitor/Errors.vue"),
            },
            {
                path:"/web-monitor/behavior",
                name:"webmonitor-behavior",
                component:()=>import("@/views/webMonitor/Behavior.vue"),
            },
            {
                path:"/web-monitor/network",
                name:"webmonitor-network",
                component:()=>import("@/views/webMonitor/Network.vue"),
            },
            // AI智能体模块
            {
                path:"/ai-agent",
                name:"ai-agent",
                component:()=>import("@/views/aiAgent/AIAgent.vue"),
                meta:{
                    needAuth:["admin","manager"]
                }
            },
        ]
    },
    {
        path:"/login",
        name:"Login",
        component:()=>import("@/views/Login.vue")
    },
    {
        path:"/:pathMatch(.*)*",
        name:"NotFound",
        component:()=>import("@/views/NotFound.vue")
    }
]

export default routes